# Generated by rebar3_nix
let
  fetchOnly = { src, ... }: src;
in
{
  builder ? fetchOnly,
  fetchHex,
  fetchgit,
  fetchFromGitHub,
  overrides ? (x: y: { }),
}:
let
  self = packages // (overrides self packages);
  packages = with self; {
    erlandono = builder {
      name = "erlandono";
      version = "3.1.3";
      src = fetchHex {
        pkg = "erlandono";
        version = "3.1.3";
        sha256 = "sha256-K/yvZZwAMsW1zv1ILrvbohqyAdFXmlRIXgkZX8IJJXc=";
      };
      beamDeps = [ ];
    };
    epgsql = builder {
      name = "epgsql";
      version = "4.7.1";
      src = fetchHex {
        pkg = "epgsql";
        version = "4.7.1";
        sha256 = "sha256-tthrfcQshVWx1OIIgOUJnW1tBTFIAA4YjlSPmOTgGDY=";
      };
      beamDeps = [ ];
    };
  };
in
self
