name: "[Nix] Build"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: "[Nix] Build"
        run: |
          nix build
