name: "[Nix] Build"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/**
      - config/**
      - include/**
      - src/**
      - test/**
      - priv/**
      - flake.nix
      - flake.lock
      - rebar.config
      - rebar.lock
      - justfile

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: "[Nix] Build"
        id: nix_build
        run: |
          nix build

      - name: "[Rebar] Compile"
        id: compile
        run: |
          nix develop .#ci --impure -c rebar3 compile
          if [ $? -eq 0 ]; then
            echo "status=passing" >> $GITHUB_OUTPUT
          else
            echo "status=failing" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: "[Rebar] Dialyzer"
        id: dialyzer
        continue-on-error: true
        run: |
          nix develop .#ci --impure -c rebar3 dialyzer
          if [ $? -eq 0 ]; then
            echo "status=passing" >> $GITHUB_OUTPUT
          else
            echo "status=failing" >> $GITHUB_OUTPUT
            exit 1
          fi

      # Generate SVG badges
      - name: "[Badge] Compile"
        uses: emibcn/badge-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          label: compile
          status: ${{ steps.compile.outputs.status }}
          color: ${{ steps.compile.outputs.status == 'passing' && 'brightgreen' || 'red' }}
          path: compile-badge.svg

      - name: "[Badge] Dialyzer"
        uses: emibcn/badge-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          label: dialyzer
          status: ${{ steps.dialyzer.outputs.status }}
          color: ${{ steps.dialyzer.outputs.status == 'passing' && 'brightgreen' || 'red' }}
          path: dialyzer-badge.svg

      - name: Upload SVG Badges
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: svg-badges
          path: |
            compile-badge.svg
            dialyzer-badge.svg
