name: "[Types] Dialyzer"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dialyzer:
    name: "Run Dialyzer"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: "Dialyzer"
        run: |
          nix develop .#ci --impure -c rebar3 dialyzer

