name: "[PostgreSQL] Integration"

on:
  workflow_call:
    inputs:
      PG_VERSION:
        required: true
        type: string

      CONTINUE_ON_ERROR:
        required: false
        type: string
        default: false

  workflow_dispatch:

  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/**
      - config/**
      - include/**
      - src/**
      - test/**
      - priv/**
      - flake.nix
      - flake.lock
      - rebar.config
      - rebar.lock
      - justfile

env:
  PGHOST: localhost
  PGPORT: 5432
  PGPASSWORD: migraterl
  PGUSER: migraterl
  PGDATABASE: migraterl
  CONTINUE_ON_ERROR: ${{ inputs.CONTINUE_ON_ERROR }}

jobs:
  integrations:
    name: "v${{ inputs.PG_VERSION }}"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:${{ inputs.PG_VERSION }}
        env:
          PGUSER: ${{ env.PGUSER }}
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_DATABASE: ${{ env.PGDATABASE }}
        options: >-
          --health-cmd "pg_isready -U migraterl"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: "[Rebar] Common Tests"
        continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
        run: |
          nix develop .#ci --impure -c just ct
          if [ $? -eq 0 ]; then
            echo "status=passing" > ct_badge.txt
          else
            echo "status=failing" > ct_badge.txt
            exit 1
          fi

      - name: Update Badges
        uses: actions/upload-artifact@v4
        with:
          name: ci-badges
          path: |
            ct_badge.txt
