name: "[PostgreSQL] Integration"

on:
  workflow_call:
    inputs:
      PG_VERSION:
        required: true
        type: string

      CONTINUE_ON_ERROR:
        required: false
        type: string
        default: false

  workflow_dispatch:
    inputs:
      PG_VERSION:
        required: true
        type: string

      CONTINUE_ON_ERROR:
        required: false
        type: string
        default: false

env:
  PGHOST: localhost
  PGPORT: 5432
  PGPASSWORD: migraterl
  PGUSER: migraterl
  PGDATABASE: migraterl
  CONTINUE_ON_ERROR: ${{ inputs.CONTINUE_ON_ERROR }}
  BADGE_NAME: "ct_badge_pg_${{ inputs.PG_VERSION }}"
  BADGE_FILE: "ct_badge_pg_${{ inputs.PG_VERSION }}.svg"

jobs:
  integrations:
    name: "v${{ inputs.PG_VERSION }}"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:${{ inputs.PG_VERSION }}
        env:
          PGUSER: ${{ env.PGUSER }}
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_DATABASE: ${{ env.PGDATABASE }}
        options: >-
          --health-cmd "pg_isready -U migraterl"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: "[Rebar] Common Tests"
        id: ct
        continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
        run: |
          nix develop .#ci --impure -c just t
          if [ $? -eq 0 ]; then
            echo "status=passing" >> $GITHUB_OUTPUT
          else
            echo "status=failing" >> $GITHUB_OUTPUT
            exit 1
          fi

      # Generate SVG badges
      - name: "[Badge] Common Tests"
        uses: emibcn/badge-action@v2
        #if: ${{ github.event_name != 'pull_request' }}
        with:
          label: compile
          status: ${{ steps.ct.outputs.status }}
          color: ${{ steps.ct.outputs.status == 'passing' && 'brightgreen' || 'red' }}
          path: ${{ env.BADGE_FILE }}

      - name: Update Badges
        uses: actions/upload-artifact@v4
        id: upload_01
        #if: ${{ github.event_name != 'pull_request' }}
        with:
          name: ${{ env.BADGE_NAME }}
          overwrite: true
          path: |
            ${{ env.BADGE_FILE }}

      - name: "Output artifact IDs"
        run: |
          echo "Artifact ID is ${{ steps.upload_01.outputs.artifact-id }}"
