name: "Simple Tests"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/**
      - src/**
      - test/**
      - database/**
      - flake.nix
      - flake.lock
      - rebar.config
      - rebar.lock
      - justfile

permissions:
  contents: read

jobs:
  simple-tests:
    name: Simple Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: "Run eunit tests"
        run: |
          nix develop .#ci --impure -c rebar3 eunit

      - name: "Get Code coverage"
        run: |
          nix develop .#ci --impure -c rebar3 eunit
