name: "[Release] Create Release"

on:
  push:
    tags:
      - 'v[0-9]^{1,3}.[0-9]^{1,3}.[0-9]^{1,3}'
  workflow_dispatch:

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.token }}

  publish-to-hex:
    name: Publish to Hex
    runs-on: ubuntu-latest
    needs: create-github-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Install Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Publish to Hex
        run: nix develop --impure -c just publish
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
